### ISSUE TITLE
Feature Request: setObject with clear/overwrite optional parameter

### ISSUE THREAD

**Issue by KrishnaPG** [jagi/meteor-reactive-map#3]
Presently, the `setObject()` method works more like appending the new keys into an existing map (rather than setting the map object values, as the name suggests).

```
var m = new ReactiveMap();
m.set(kv1);
m.set(kv2);
```

The result is `m` contains `kv1 + kv2` properties (ratherthan setting `m` to `kv2`).

To reset the map with another object completely, we have to issue a `clear` first and then `setObject` next. This results in unnecessary dependency callbacks.

```
m.set(kv1);
m.clear();
m.set(kv2);
```

It would be great if `setObject` method is made to accept additional optional parameter (something like overwrite / clear) that lets one clear the existing map-values fully and loads the supplied object as-is (instead of adding it).

```
m.set(kv1);
m.setObject(kv2, clear=true); // now m == kv2
```

**Comment by lukejagodzinski** [comment]
First of all, you can't use `setObject` method directly so I don't know how you are using it. The `setObject` method is private and can be accessed from the level of `ReactiveMap`.

You can do the following things.
- Set single element

``` js
var rm = new ReactiveMap();
rm.set('key1', 'value');
rm.set('key2', {someObject: 'abc'});
```
- Multiple values at once

``` js
var rm = new ReactiveMap();
rm.set({
  key1: 'value',
  key2: 'value'
});
```

**Comment by KrishnaPG** [comment]
Thanks.

The issue is more with 'how to reset a ReactiveMap object to brand new map object'. 

In your example, if you do the below

```
var rm = new ReactiveMap();
rm.set({
  key1: 'value',
  key2: 'value'
});
rm.set({
 key3: 'value',
 key4:'value'
});
```

`rm` now contains all keys, rather than the later set keys only (which may be required sometimes, but `set` is not really the right name to use for `append keys` functionality). Hence the above post and request for optional argument. If you want to retain `setObject` as private thats a different story.

**Comment by lukejagodzinski** [comment]
ReactiveMap is a copy of Map implementation from ES6. I don't want to change its behavior. If you know how to use Map you know how to use ReactiveMap. In your use case you should clear map before setting new values:

``` js
var rm = new ReactiveMap();
rm.set({
  key1: 'value',
  key2: 'value'
});
rm.clear();
rm.set({
 key3: 'value',
 key4:'value'
});
```
