### ISSUE TITLE
Add EJSON to package.js

### ISSUE THREAD

**Issue by dalgard** [jagi/meteor-reactive-map#5]
When using `jagi:reactive-map` in a package, it fails, because EJSON isn't added as an explicit dependency.

**Comment by lukejagodzinski** [comment]
Oh thanks for noticing it. I will update it.

**Comment by lukejagodzinski** [comment]
OK new version published. Sorry that I took me so long but I have a lot of work on making documentation for Astronomy and fixing bugs.

**Comment by dalgard** [comment]
:+1:
