### ISSUE TITLE
all/entries aliases?

### ISSUE THREAD

**Issue by rclai** [jagi/meteor-reactive-map#6]
If one is an alias of another, why are they [implemented differently](https://github.com/jagi/meteor-reactive-map/blob/740747a416efa4caf928ac8ac44b51c910fc2e00/lib/reactive_map.js#L52-L69)?

**Comment by lukejagodzinski** [comment]
As you may see it's for 2.0 version of this package and the documentation is still for 1.0. I will be publishing it probably tomorrow. The `entries` method will work exactly the same as the one in the `Map` container. Right now it's not working correctly. It should return array of arrays `[key, value]`.

**Comment by lukejagodzinski** [comment]
Version 2.0 released and there is a difference in how `entries` and `all` methods work. I will describe it in a second in the README.
